name: flutter_tricorder
description: A custom package to handle Tricorder API


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2