name: wycorder
version: 0.0.1
summary: A self-screening tool for COVID
description: A self-screening tool for COVID

confinement: strict
base: core18
grade: devel

apps:
  wycorder:
    command: wycorder
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network

parts:
  wycorder:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application